#!/usr/bin/perl
package Bitcoin::Electrum::Mnemonic;
use strict;
use integer;

our @words = split / +|\n/, join '', <DATA>;
my $n = @words;
my $i; my %index; $index{$_} = $i++ for @words;

sub encode {
    my $msg = shift;
    my @out;
    for my $i (0 .. length( $msg )/8 - 1) {
	my $x = hex substr $msg, 8*$i, 8;
	my $u = $x % $n;
	my $v = ( $x/$n + $u ) % $n;
	my $w = ( $x/$n/$n + $v ) % $n;
	push @out, @words[$u,$v,$w];
    }
    return @out;
}
sub decode {
    my @wlist = @_;
    my $out = '';
    for my $i (0 .. @wlist/3 - 1) {
	my @word = @wlist[map 3*$i+$_, 0, 1, 2];
	my $u =  $index{$word[0]};
	my $v =  $index{$word[1]} % $n;
	my $w =  $index{$word[2]} % $n;
	my $x = $u + $n*(($v-$u) % $n) + $n*$n*(($w-$v) % $n);
	$out .= sprintf "%x", $x;
    }
    return $out;
}

1;

=head1 TITLE

Mnemonic

=head1 SYNOPSIS

    use Mnemonic;

    my @msg = Mnemonic::encode 420713AA;	# @msg now constains 'back although pocket';

    print uc Mnemonic::decode @msg;		# prints back 420713AA

=head1 DESCRIPTION

This module is a translation of Electrum's mnemonic module.  It aims to provide
a solution for memorizing random number generator seeds.

=head2 BUGS

This should work fine, provided that the number of bytes on input is a multiple of 4.

=cut

__DATA__
LIKE JUST LOVE KNOW NEVER WANT TIME OUT THERE MAKE LOOK EYE DOWN ONLY THINK
HEART BACK THEN INTO ABOUT MORE AWAY STILL THEM TAKE THING EVEN THROUGH LONG
ALWAYS WORLD TOO FRIEND TELL TRY HAND THOUGHT OVER HERE OTHER NEED SMILE AGAIN
MUCH CRY BEEN NIGHT EVER LITTLE SAID END SOME THOSE AROUND MIND PEOPLE GIRL
LEAVE DREAM LEFT TURN MYSELF GIVE NOTHING REALLY OFF BEFORE SOMETHING FIND WALK
WISH GOOD ONCE PLACE ASK STOP KEEP WATCH SEEM EVERYTHING WAIT GOT YET MADE
REMEMBER START ALONE RUN HOPE MAYBE BELIEVE BODY HATE AFTER CLOSE TALK STAND
OWN EACH HURT HELP HOME GOD SOUL NEW MANY TWO INSIDE SHOULD TRUE FIRST FEAR
MEAN BETTER PLAY ANOTHER GONE CHANGE USE WONDER SOMEONE HAIR COLD OPEN BEST ANY
BEHIND HAPPEN WATER DARK LAUGH STAY FOREVER NAME WORK SHOW SKY BREAK CAME DEEP
DOOR PUT BLACK TOGETHER UPON HAPPY SUCH GREAT WHITE MATTER FILL PAST PLEASE
BURN CAUSE ENOUGH TOUCH MOMENT SOON VOICE SCREAM ANYTHING STARE SOUND RED
EVERYONE HIDE KISS TRUTH DEATH BEAUTIFUL MINE BLOOD BROKEN VERY PASS NEXT
FORGET TREE WRONG AIR MOTHER UNDERSTAND LIP HIT WALL MEMORY SLEEP FREE HIGH
REALIZE SCHOOL MIGHT SKIN SWEET PERFECT BLUE KILL BREATH DANCE AGAINST FLY
BETWEEN GROW STRONG UNDER LISTEN BRING SOMETIMES SPEAK PULL PERSON BECOME
FAMILY BEGIN GROUND REAL SMALL FATHER SURE FEET REST YOUNG FINALLY LAND ACROSS
TODAY DIFFERENT GUY LINE FIRE REASON REACH SECOND SLOWLY WRITE EAT SMELL MOUTH
STEP LEARN THREE FLOOR PROMISE BREATHE DARKNESS PUSH EARTH GUESS SAVE SONG
ABOVE ALONG BOTH COLOR HOUSE ALMOST SORRY ANYMORE BROTHER OKAY DEAR GAME FADE
ALREADY APART WARM BEAUTY HEARD NOTICE QUESTION SHINE BEGAN PIECE WHOLE SHADOW
SECRET STREET WITHIN FINGER POINT MORNING WHISPER CHILD MOON GREEN STORY GLASS
KID SILENCE SINCE SOFT YOURSELF EMPTY SHALL ANGEL ANSWER BABY BRIGHT DAD PATH
WORRY HOUR DROP FOLLOW POWER WAR HALF FLOW HEAVEN ACT CHANCE FACT LEAST TIRED
CHILDREN NEAR QUITE AFRAID RISE SEA TASTE WINDOW COVER NICE TRUST LOT SAD COOL
FORCE PEACE RETURN BLIND EASY READY ROLL ROSE DRIVE HELD MUSIC BENEATH HANG MOM
PAINT EMOTION QUIET CLEAR CLOUD FEW PRETTY BIRD OUTSIDE PAPER PICTURE FRONT
ROCK SIMPLE ANYONE MEANT REALITY ROAD SENSE WASTE BIT LEAF THANK HAPPINESS MEET
MEN SMOKE TRULY DECIDE SELF AGE BOOK FORM ALIVE CARRY ESCAPE DAMN INSTEAD ABLE
ICE MINUTE THROW CATCH LEG RING COURSE GOODBYE LEAD POEM SICK CORNER DESIRE
KNOWN PROBLEM REMIND SHOULDER SUPPOSE TOWARD WAVE DRINK JUMP WOMAN PRETEND
SISTER WEEK HUMAN JOY CRACK GREY PRAY SURPRISE DRY KNEE LESS SEARCH BLEED
CAUGHT CLEAN EMBRACE FUTURE KING SON SORROW CHEST HUG REMAIN SAT WORTH BLOW
DADDY FINAL PARENT TIGHT ALSO CREATE LONELY SAFE CROSS DRESS EVIL SILENT BONE
FATE PERHAPS ANGER CLASS SCAR SNOW TINY TONIGHT CONTINUE CONTROL DOG EDGE
MIRROR MONTH SUDDENLY COMFORT GIVEN LOUD QUICKLY GAZE PLAN RUSH STONE TOWN
BATTLE IGNORE SPIRIT STOOD STUPID YOURS BROWN BUILD DUST HEY KEPT PAY PHONE
TWIST ALTHOUGH BALL BEYOND HIDDEN NOSE TAKEN FAIL FLOAT PURE SOMEHOW WASH WRAP
ANGRY CHEEK CREATURE FORGOTTEN HEAT RIP SINGLE SPACE SPECIAL WEAK WHATEVER YELL
ANYWAY BLAME JOB CHOOSE COUNTRY CURSE DRIFT ECHO FIGURE GREW LAUGHTER NECK
SUFFER WORSE YEAH DISAPPEAR FOOT FORWARD KNIFE MESS SOMEWHERE STOMACH STORM BEG
IDEA LIFT OFFER BREEZE FIELD FIVE OFTEN SIMPLY STUCK WIN ALLOW CONFUSE ENJOY
EXCEPT FLOWER SEEK STRENGTH CALM GRIN GUN HEAVY HILL LARGE OCEAN SHOE SIGH
STRAIGHT SUMMER TONGUE ACCEPT CRAZY EVERYDAY EXIST GRASS MISTAKE SENT SHUT
SURROUND TABLE ACHE BRAIN DESTROY HEAL NATURE SHOUT SIGN STAIN CHOICE DOUBT
GLANCE GLOW MOUNTAIN QUEEN STRANGER THROAT TOMORROW CITY EITHER FISH FLAME
RATHER SHAPE SPIN SPREAD ASH DISTANCE FINISH IMAGE IMAGINE IMPORTANT NOBODY
SHATTER WARMTH BECAME FEED FLESH FUNNY LUST SHIRT TROUBLE YELLOW ATTENTION BARE
BITE MONEY PROTECT AMAZE APPEAR BORN CHOKE COMPLETELY DAUGHTER FRESH FRIENDSHIP
GENTLE PROBABLY SIX DESERVE EXPECT GRAB MIDDLE NIGHTMARE RIVER THOUSAND WEIGHT
WORST WOUND BARELY BOTTLE CREAM REGRET RELATIONSHIP STICK TEST CRUSH ENDLESS
FAULT ITSELF RULE SPILL ART CIRCLE JOIN KICK MASK MASTER PASSION QUICK RAISE
SMOOTH UNLESS WANDER ACTUALLY BROKE CHAIR DEAL FAVORITE GIFT NOTE NUMBER SWEAT
BOX CHILL CLOTHES LADY MARK PARK POOR SADNESS TIE ANIMAL BELONG BRUSH CONSUME
DAWN FOREST INNOCENT PEN PRIDE STREAM THICK CLAY COMPLETE COUNT DRAW FAITH
PRESS SILVER STRUGGLE SURFACE TAUGHT TEACH WET BLESS CHASE CLIMB ENTER LETTER
MELT METAL MOVIE STRETCH SWING VISION WIFE BESIDE CRASH FORGOT GUIDE HAUNT JOKE
KNOCK PLANT POUR PROVE REVEAL STEAL STUFF TRIP WOOD WRIST BOTHER BOTTOM CRAWL
CROWD FIX FORGIVE FROWN GRACE LOOSE LUCKY PARTY RELEASE SURELY SURVIVE TEACHER
GENTLY GRIP SPEED SUICIDE TRAVEL TREAT VEIN WRITTEN CAGE CHAIN CONVERSATION
DATE ENEMY HOWEVER INTEREST MILLION PAGE PINK PROUD SWAY THEMSELVES WINTER
CHURCH CRUEL CUP DEMON EXPERIENCE FREEDOM PAIR POP PURPOSE RESPECT SHOOT SOFTLY
STATE STRANGE BAR BIRTH CURL DIRT EXCUSE LORD LOVELY MONSTER ORDER PACK PANTS
POOL SCENE SEVEN SHAME SLIDE UGLY AMONG BLADE BLONDE CLOSET CREEK DENY DRUG
ETERNITY GAIN GRADE HANDLE KEY LINGER PALE PREPARE SWALLOW SWIM TREMBLE WHEEL
WON CAST CIGARETTE CLAIM COLLEGE DIRECTION DIRTY GATHER GHOST HUNDRED LOSS LUNG
ORANGE PRESENT SWEAR SWIRL TWICE WILD BITTER BLANKET DOCTOR EVERYWHERE FLASH
GROWN KNOWLEDGE NUMB PRESSURE RADIO REPEAT RUIN SPEND UNKNOWN BUY CLOCK DEVIL
EARLY FALSE FANTASY POUND PRECIOUS REFUSE SHEET TEETH WELCOME ADD AHEAD BLOCK
BURY CARESS CONTENT DEPTH DESPITE DISTANT MARRY PURPLE THREW WHENEVER BOMB DULL
EASILY GRASP HOSPITAL INNOCENCE NORMAL RECEIVE REPLY RHYME SHADE SOMEDAY SWORD
TOE VISIT ASLEEP BOUGHT CENTER CONSIDER FLAT HERO HISTORY INK INSANE MUSCLE
MYSTERY POCKET REFLECTION SHOVE SILENTLY SMART SOLDIER SPOT STRESS TRAIN TYPE
VIEW WHETHER BUS ENERGY EXPLAIN HOLY HUNGER INCH MAGIC MIX NOISE NOWHERE PRAYER
PRESENCE SHOCK SNAP SPIDER STUDY THUNDER TRAIL ADMIT AGREE BAG BANG BOUND
BUTTERFLY CUTE EXACTLY EXPLODE FAMILIAR FOLD FURTHER PIERCE REFLECT SCENT
SELFISH SHARP SINK SPRING STUMBLE UNIVERSE WEEP WOMEN WONDERFUL ACTION ANCIENT
ATTEMPT AVOID BIRTHDAY BRANCH CHOCOLATE CORE DEPRESS DRUNK ESPECIALLY FOCUS
FRUIT HONEST MATCH PALM PERFECTLY PILLOW PITY POISON ROAR SHIFT SLIGHTLY THUMP
TRUCK TUNE TWENTY UNABLE WIPE WROTE COAT CONSTANT DINNER DROVE EGG ETERNAL
FLIGHT FLOOD FRAME FREAK GASP GLAD HOLLOW MOTION PEER PLASTIC ROOT SCREEN
SEASON STING STRIKE TEAM UNLIKE VICTIM VOLUME WARN WEIRD ATTACK AWAIT AWAKE
BUILT CHARM CRAVE DESPAIR FOUGHT GRANT GRIEF HORSE LIMIT MESSAGE RIPPLE SANITY
SCATTER SERVE SPLIT STRING TRICK ANNOY BLUR BOAT BRAVE CLEARLY CLING CONNECT
FIST FORTH IMAGINATION IRON JOCK JUDGE LESSON MILK MISERY NAIL NAKED OURSELVES
POET POSSIBLE PRINCESS SAIL SIZE SNAKE SOCIETY STROKE TORTURE TOSS TRACE WISE
BLOOM BULLET CELL CHECK COST DARLING DURING FOOTSTEP FRAGILE HALLWAY HARDLY
HORIZON INVISIBLE JOURNEY MIDNIGHT MUD NOD PAUSE RELAX SHIVER SUDDEN VALUE
YOUTH ABUSE ADMIRE BLINK BREAST BRUISE CONSTANTLY COUPLE CREEP CURVE DIFFERENCE
DUMB EMPTINESS GOTTA HONOR PLAIN PLANET RECALL RUB SHIP SLAM SOAR SOMEBODY
TIGHTLY WEATHER ADORE APPROACH BOND BREAD BURST CANDLE COFFEE COUSIN CRIME
DESERT FLUTTER FROZEN GRAND HEEL HELLO LANGUAGE LEVEL MOVEMENT PLEASURE
POWERFUL RANDOM RHYTHM SETTLE SILLY SLAP SORT SPOKEN STEEL THREATEN TUMBLE
UPSET ASIDE AWKWARD BEE BLANK BOARD BUTTON CARD CAREFULLY COMPLAIN CRAP DEEPLY
DISCOVER DRAG DREAD EFFORT ENTIRE FAIRY GIANT GOTTEN GREET ILLUSION JEANS LEAP
LIQUID MARCH MEND NERVOUS NINE REPLACE ROPE SPINE STOLE TERROR ACCIDENT APPLE
BALANCE BOOM CHILDHOOD COLLECT DEMAND DEPRESSION EVENTUALLY FAINT GLARE GOAL
GROUP HONEY KITCHEN LAID LIMB MACHINE MERE MOLD MURDER NERVE PAINFUL POETRY
PRINCE RABBIT SHELTER SHORE SHOWER SOOTHE STAIR STEADY SUNLIGHT TANGLE TEASE
TREASURE UNCLE BEGUN BLISS CANVAS CHEER CLAW CLUTCH COMMIT CRIMSON CRYSTAL
DELIGHT DOLL EXISTENCE EXPRESS FOG FOOTBALL GAY GOOSE GUARD HATRED ILLUMINATE
MASS MATH MOURN RICH ROUGH SKIP STIR STUDENT STYLE SUPPORT THORN TOUGH YARD
YEARN YESTERDAY ADVICE APPRECIATE AUTUMN BANK BEAM BOWL CAPTURE CARVE COLLAPSE
CONFUSION CREATION DOVE FEATHER GIRLFRIEND GLORY GOVERNMENT HARSH HOP INNER
LOSER MOONLIGHT NEIGHBOR NEITHER PEACH PIG PRAISE SCREW SHIELD SHIMMER SNEAK
STAB SUBJECT THROUGHOUT THROWN TOWER TWIRL WOW ARMY ARRIVE BATHROOM BUMP CEASE
COOKIE COUCH COURAGE DIM GUILT HOWL HUM HUSBAND INSULT LED LUNCH MOCK MOSTLY
NATURAL NEARLY NEEDLE NERD PEACEFUL PERFECTION PILE PRICE REMOVE ROAM SANCTUARY
SERIOUS SHINY SHOOK SOB STOLEN TAP VAIN VOID WARRIOR WRINKLE AFFECTION
APOLOGIZE BLOSSOM BOUNCE BRIDGE CHEAP CRUMBLE DECISION DESCEND DESPERATELY DIG
DOT FLIP FRIGHTEN HEARTBEAT HUGE LAZY LICK ODD OPINION PROCESS PUZZLE QUIETLY
RETREAT SCORE SENTENCE SEPARATE SITUATION SKILL SOAK SQUARE STRAY TAINT TASK
TIDE UNDERNEATH VEIL WHISTLE ANYWHERE BEDROOM BID BLOODY BURDEN CAREFUL COMPARE
CONCERN CURTAIN DECAY DEFEAT DESCRIBE DOUBLE DREAMER DRIVER DWELL EVENING FLARE
FLICKER GRANDMA GUITAR HARM HORRIBLE HUNGRY INDEED LACE MELODY MONKEY NATION
OBJECT OBVIOUSLY RAINBOW SALT SCRATCH SHOWN SHY STAGE STUN THIRD TICKLE USELESS
WEAKNESS WORSHIP WORTHLESS AFTERNOON BEARD BOYFRIEND BUBBLE BUSY CERTAIN CHIN
CONCRETE DESK DIAMOND DOOM DRAWN DUE FELICITY FREEZE FROST GARDEN GLIDE HARMONY
HOPEFULLY HUNT JEALOUS LIGHTNING MAMA MERCY PEEL PHYSICAL POSITION PULSE PUNCH
QUIT RANT RESPOND SALTY SANE SATISFY SAVIOR SHEEP SLEPT SOCIAL SPORT TUCK UTTER
VALLEY WOLF AIM ALAS ALTER ARROW AWAKEN BEATEN BELIEF BRAND CEILING CHEESE CLUE
CONFIDENCE CONNECTION DAILY DISGUISE EAGER ERASE ESSENCE EVERYTIME EXPRESSION
FAN FLAG FLIRT FOUL FUR GIGGLE GLORIOUS IGNORANCE LAW LIFELESS MEASURE MIGHTY
MUSE NORTH OPPOSITE PARADISE PATIENCE PATIENT PENCIL PETAL PLATE PONDER
POSSIBLY PRACTICE SLICE SPELL STOCK STRIFE STRIP SUFFOCATE SUIT TENDER TOOL
TRADE VELVET VERSE WAIST WITCH AUNT BENCH BOLD CAP CERTAINLY CLICK COMPANION
CREATOR DART DELICATE DETERMINE DISH DRAGON DRAMA DRUM DUDE EVERYBODY FEAST
FOREHEAD FORMER FRIGHT FULLY GAS HOOK HURL INVITE JUICE MANAGE MORAL POSSESS
RAW REBEL ROYAL SCALE SCARY SEVERAL SLIGHT STUBBORN SWELL TALENT TEA TERRIBLE
THREAD TORMENT TRICKLE USUALLY VAST VIOLENCE WEAVE ACID AGONY ASHAMED AWE BELLY
BLEND BLUSH CHARACTER CHEAT COMMON COMPANY COWARD CREAK DANGER DEADLY DEFENSE
DEFINE DEPEND DESPERATE DESTINATION DEW DUCK DUSTY EMBARRASS ENGINE EXAMPLE
EXPLORE FOE FREELY FRUSTRATE GENERATION GLOVE GUILTY HEALTH HURRY IDIOT
IMPOSSIBLE INHALE JAW KINGDOM MENTION MIST MOAN MUMBLE MUTTER OBSERVE ODE
PATHETIC PATTERN PIE PREFER PUFF RAPE RARE REVENGE RUDE SCRAPE SPIRAL SQUEEZE
STRAIN SUNSET SUSPEND SYMPATHY THIGH THRONE TOTAL UNSEEN WEAPON WEARY


